trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  dotNetVersion: '10.x'
  azureSubscription: 'AzureConnection-Students' 
  webAppName: 'ERMSBE'
  sonarProjectKey: 'EnterpriseResourcePlanningSystem_EnterpriseResourcePlanningSystem_BE'
  sonarOrg: 'enterpriseresourceplanningsystem'

stages:
- stage: Build
  displayName: 'Build and Package'
  jobs:
  - job: Build
    displayName: 'Build API'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET 10 SDK'
      inputs:
        packageType: 'sdk'
        version: '$(dotNetVersion)'
        includePreviewVersions: true

    - script: dotnet tool install --global dotnet-sonarscanner
      displayName: 'Install SonarScanner Tool'

    - script: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet sonarscanner begin /k:"$(sonarProjectKey)" \
        /o:"$(sonarOrg)" \
        /d:sonar.token="$SONAR_TOKEN_ENV" \
        /d:sonar.host.url="https://sonarcloud.io"
      displayName: 'SonarScanner Begin'
      env: 
        SONAR_TOKEN_ENV: $(SONAR_TOKEN)

    - task: DotNetCoreCLI@2
      displayName: 'Restore Dependencies'
      inputs:
        command: 'restore'
        projects: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-restore'
    - script: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet sonarscanner end /d:sonar.token="$(SONAR_TOKEN)"
      displayName: 'SonarScanner End'

    - task: DotNetCoreCLI@2
      displayName: 'Publish API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/ERMS.API.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --runtime linux-x64 --self-contained false'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy to Azure App Service'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy API'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/api/*.zip'
              runtimeStack: 'DOTNETCORE|10.0'
