trigger:
  branches:
    include:
    - dev
    
pr: none 
variables:
  dockerRegistryConnection: 'DockerHubConnection'
  imageName: 'baotcq/erms-api'
  
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_And_Push
  displayName: 'Đóng gói & Đẩy Docker Image'
  jobs:
  - job: Build
    displayName: 'Build Docker API'
    steps:
    - task: Docker@2
      displayName: 'Build code C# và Push lên Docker Hub'
      inputs:
        containerRegistry: '$(dockerRegistryConnection)'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          $(Build.SourceBranchName)

- stage: Update_Manifest
  displayName: 'Cập nhật kho hạ tầng GitOps'
  dependsOn: Build_And_Push
  condition: succeeded()
  jobs:
  - job: UpdateConfig
    displayName: 'Báo cho ArgoCD cập nhật'
    steps:
    - script: |
        set -e
        git config --global user.email "bot@erms-project.com"
        git config --global user.name "GitOps Bot"
        
        git clone https://$MY_PAT@dev.azure.com/EnterpriseResourcePlanningSystem/_git/EnterpriseResourcePlanningSystem_BE manifests
        
       
        cd manifests/erms-api/overlays/dev
        
        sed -i "s/newTag:.*/newTag: '$(tag)'/" kustomization.yaml
        git add kustomization.yaml
        git commit -m "Auto-update DEV environment to image tag: $(tag)"
        git push origin master
      displayName: 'Cập nhật Kustomize cho DEV'
      env:
        MY_PAT: $(PAT)